// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 22 May 2024 15:11:09 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "sql.h"
#include "sqlext.h"
#include "stdint.h"
#include "sqlucode.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

