// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 13 Jan 2023 14:11:07 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "sql.h"
#include "sqlext.h"
#include "stdint.h"
#include "sqlucode.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

