// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Oct 2023 12:49:57 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package api provides Go bindings for unixodbc.
*/
package api
