// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 13 Jan 2023 14:11:07 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package api

/*
#cgo linux LDFLAGS: -lodbc
#include "sql.h"
#include "sqlext.h"
#include "stdint.h"
#include "sqlucode.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// SQLCHAR type as declared in include/sqltypes.h:125
type SQLCHAR byte

// SQLDATE type as declared in include/sqltypes.h:128
type SQLDATE byte

// SQLDECIMAL type as declared in include/sqltypes.h:129
type SQLDECIMAL byte

// SQLDOUBLE type as declared in include/sqltypes.h:130
type SQLDOUBLE float64

// SQLFLOAT type as declared in include/sqltypes.h:131
type SQLFLOAT float64

// SQLINTEGER type as declared in include/sqltypes.h:160
type SQLINTEGER int32

// SQLUINTEGER type as declared in include/sqltypes.h:161
type SQLUINTEGER uint32

// SQLLEN type as declared in include/sqltypes.h:162
type SQLLEN int64

// SQLULEN type as declared in include/sqltypes.h:163
type SQLULEN uint64

// SQLSETPOSIROW type as declared in include/sqltypes.h:164
type SQLSETPOSIROW uint64

// SQLNUMERIC type as declared in include/sqltypes.h:197
type SQLNUMERIC byte

// SQLPOINTER type as declared in include/sqltypes.h:200
type SQLPOINTER unsafe.Pointer

// SQLREAL type as declared in include/sqltypes.h:203
type SQLREAL float32

// SQLSMALLINT type as declared in include/sqltypes.h:206
type SQLSMALLINT int16

// SQLUSMALLINT type as declared in include/sqltypes.h:207
type SQLUSMALLINT uint16

// SQLTIME type as declared in include/sqltypes.h:210
type SQLTIME byte

// SQLTIMESTAMP type as declared in include/sqltypes.h:211
type SQLTIMESTAMP byte

// SQLVARCHAR type as declared in include/sqltypes.h:212
type SQLVARCHAR byte

// SQLRETURN type as declared in include/sqltypes.h:215
type SQLRETURN int16

// SQLHANDLE type as declared in include/sqltypes.h:218
type SQLHANDLE unsafe.Pointer

// SQLHENV type as declared in include/sqltypes.h:219
type SQLHENV unsafe.Pointer

// SQLHDBC type as declared in include/sqltypes.h:220
type SQLHDBC unsafe.Pointer

// SQLHSTMT type as declared in include/sqltypes.h:221
type SQLHSTMT unsafe.Pointer

// SQLHDESC type as declared in include/sqltypes.h:222
type SQLHDESC unsafe.Pointer

// SQLSCHAR type as declared in include/sqltypes.h:258
type SQLSCHAR int8

// SQLHWND type as declared in include/sqltypes.h:278
type SQLHWND unsafe.Pointer

// SQL_DATE_STRUCT as declared in include/sqltypes.h:295
type SQL_DATE_STRUCT struct {
	Year           SQLSMALLINT
	Month          SQLUSMALLINT
	Day            SQLUSMALLINT
	refecf4b83f    *C.SQL_DATE_STRUCT
	allocsecf4b83f interface{}
}

// SQL_TIME_STRUCT as declared in include/sqltypes.h:306
type SQL_TIME_STRUCT struct {
	Hour           SQLUSMALLINT
	Minute         SQLUSMALLINT
	Second         SQLUSMALLINT
	ref51b6c82a    *C.SQL_TIME_STRUCT
	allocs51b6c82a interface{}
}

// SQL_TIMESTAMP_STRUCT as declared in include/sqltypes.h:321
type SQL_TIMESTAMP_STRUCT struct {
	Year           SQLSMALLINT
	Month          SQLUSMALLINT
	Day            SQLUSMALLINT
	Hour           SQLUSMALLINT
	Minute         SQLUSMALLINT
	Second         SQLUSMALLINT
	Fraction       SQLUINTEGER
	ref863f74dc    *C.SQL_TIMESTAMP_STRUCT
	allocs863f74dc interface{}
}

// SQL_YEAR_MONTH_STRUCT as declared in include/sqltypes.h:350
type SQL_YEAR_MONTH_STRUCT struct {
	Year           SQLUINTEGER
	Month          SQLUINTEGER
	ref8e33cf55    *C.SQL_YEAR_MONTH_STRUCT
	allocs8e33cf55 interface{}
}

// SQL_DAY_SECOND_STRUCT as declared in include/sqltypes.h:359
type SQL_DAY_SECOND_STRUCT struct {
	Day            SQLUINTEGER
	Hour           SQLUINTEGER
	Minute         SQLUINTEGER
	Second         SQLUINTEGER
	Fraction       SQLUINTEGER
	ref74d37172    *C.SQL_DAY_SECOND_STRUCT
	allocs74d37172 interface{}
}

// SQL_INTERVAL_STRUCT as declared in include/sqltypes.h:370
type SQL_INTERVAL_STRUCT struct {
	Interval_type  SQLINTERVAL
	Interval_sign  SQLSMALLINT
	ref88eb89bb    *C.SQL_INTERVAL_STRUCT
	allocs88eb89bb interface{}
}

// SQLBIGINT type as declared in include/sqltypes.h:416
type SQLBIGINT int64

// SQLUBIGINT type as declared in include/sqltypes.h:419
type SQLUBIGINT uint64

// SQL_NUMERIC_STRUCT as declared in include/sqltypes.h:434
type SQL_NUMERIC_STRUCT struct {
	Precision      SQLCHAR
	Scale          SQLSCHAR
	Sign           SQLCHAR
	Val            [16]SQLCHAR
	ref56ec20d2    *C.SQL_NUMERIC_STRUCT
	allocs56ec20d2 interface{}
}

// SQLGUID as declared in include/sqltypes.h:457
type SQLGUID struct {
	Data1          uint32
	Data2          uint16
	Data3          uint16
	Data4          [8]byte
	refe93ebf54    *C.SQLGUID
	allocse93ebf54 interface{}
}

// SQLWCHAR type as declared in include/sqltypes.h:463
type SQLWCHAR uint16

// SQLTCHAR type as declared in include/sqltypes.h:468
type SQLTCHAR byte
