// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 22 May 2024 10:01:23 MDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package api

/*
#cgo linux LDFLAGS: -lodbc
#include "sql.h"
#include "sqlext.h"
#include "stdint.h"
#include "sqlucode.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// SQLCHAR type as declared in include/sqltypes.h:129
type SQLCHAR byte

// SQLDATE type as declared in include/sqltypes.h:132
type SQLDATE byte

// SQLDECIMAL type as declared in include/sqltypes.h:133
type SQLDECIMAL byte

// SQLDOUBLE type as declared in include/sqltypes.h:134
type SQLDOUBLE float64

// SQLFLOAT type as declared in include/sqltypes.h:135
type SQLFLOAT float64

// SQLINTEGER type as declared in include/sqltypes.h:164
type SQLINTEGER int32

// SQLUINTEGER type as declared in include/sqltypes.h:165
type SQLUINTEGER uint32

// SQLLEN type as declared in include/sqltypes.h:166
type SQLLEN int64

// SQLULEN type as declared in include/sqltypes.h:167
type SQLULEN uint64

// SQLSETPOSIROW type as declared in include/sqltypes.h:168
type SQLSETPOSIROW uint64

// SQLNUMERIC type as declared in include/sqltypes.h:201
type SQLNUMERIC byte

// SQLPOINTER type as declared in include/sqltypes.h:204
type SQLPOINTER unsafe.Pointer

// SQLREAL type as declared in include/sqltypes.h:207
type SQLREAL float32

// SQLSMALLINT type as declared in include/sqltypes.h:210
type SQLSMALLINT int16

// SQLUSMALLINT type as declared in include/sqltypes.h:211
type SQLUSMALLINT uint16

// SQLTIME type as declared in include/sqltypes.h:214
type SQLTIME byte

// SQLTIMESTAMP type as declared in include/sqltypes.h:215
type SQLTIMESTAMP byte

// SQLVARCHAR type as declared in include/sqltypes.h:216
type SQLVARCHAR byte

// SQLRETURN type as declared in include/sqltypes.h:219
type SQLRETURN int16

// SQLHANDLE type as declared in include/sqltypes.h:222
type SQLHANDLE unsafe.Pointer

// SQLHENV type as declared in include/sqltypes.h:223
type SQLHENV unsafe.Pointer

// SQLHDBC type as declared in include/sqltypes.h:224
type SQLHDBC unsafe.Pointer

// SQLHSTMT type as declared in include/sqltypes.h:225
type SQLHSTMT unsafe.Pointer

// SQLHDESC type as declared in include/sqltypes.h:226
type SQLHDESC unsafe.Pointer

// SQLSCHAR type as declared in include/sqltypes.h:262
type SQLSCHAR int8

// SQLHWND type as declared in include/sqltypes.h:282
type SQLHWND unsafe.Pointer

// SQL_DATE_STRUCT as declared in include/sqltypes.h:299
type SQL_DATE_STRUCT struct {
	Year           SQLSMALLINT
	Month          SQLUSMALLINT
	Day            SQLUSMALLINT
	refecf4b83f    *C.SQL_DATE_STRUCT
	allocsecf4b83f interface{}
}

// SQL_TIME_STRUCT as declared in include/sqltypes.h:310
type SQL_TIME_STRUCT struct {
	Hour           SQLUSMALLINT
	Minute         SQLUSMALLINT
	Second         SQLUSMALLINT
	ref51b6c82a    *C.SQL_TIME_STRUCT
	allocs51b6c82a interface{}
}

// SQL_TIMESTAMP_STRUCT as declared in include/sqltypes.h:325
type SQL_TIMESTAMP_STRUCT struct {
	Year           SQLSMALLINT
	Month          SQLUSMALLINT
	Day            SQLUSMALLINT
	Hour           SQLUSMALLINT
	Minute         SQLUSMALLINT
	Second         SQLUSMALLINT
	Fraction       SQLUINTEGER
	ref863f74dc    *C.SQL_TIMESTAMP_STRUCT
	allocs863f74dc interface{}
}

// SQL_YEAR_MONTH_STRUCT as declared in include/sqltypes.h:354
type SQL_YEAR_MONTH_STRUCT struct {
	Year           SQLUINTEGER
	Month          SQLUINTEGER
	ref8e33cf55    *C.SQL_YEAR_MONTH_STRUCT
	allocs8e33cf55 interface{}
}

// SQL_DAY_SECOND_STRUCT as declared in include/sqltypes.h:363
type SQL_DAY_SECOND_STRUCT struct {
	Day            SQLUINTEGER
	Hour           SQLUINTEGER
	Minute         SQLUINTEGER
	Second         SQLUINTEGER
	Fraction       SQLUINTEGER
	ref74d37172    *C.SQL_DAY_SECOND_STRUCT
	allocs74d37172 interface{}
}

// SQL_INTERVAL_STRUCT as declared in include/sqltypes.h:374
type SQL_INTERVAL_STRUCT struct {
	Interval_type  SQLINTERVAL
	Interval_sign  SQLSMALLINT
	ref88eb89bb    *C.SQL_INTERVAL_STRUCT
	allocs88eb89bb interface{}
}

// SQLBIGINT type as declared in include/sqltypes.h:420
type SQLBIGINT int64

// SQLUBIGINT type as declared in include/sqltypes.h:423
type SQLUBIGINT uint64

// SQL_NUMERIC_STRUCT as declared in include/sqltypes.h:438
type SQL_NUMERIC_STRUCT struct {
	Precision      SQLCHAR
	Scale          SQLSCHAR
	Sign           SQLCHAR
	Val            [16]SQLCHAR
	ref56ec20d2    *C.SQL_NUMERIC_STRUCT
	allocs56ec20d2 interface{}
}

// SQLGUID as declared in include/sqltypes.h:461
type SQLGUID struct {
	Data1          uint32
	Data2          uint16
	Data3          uint16
	Data4          [8]byte
	refe93ebf54    *C.SQLGUID
	allocse93ebf54 interface{}
}

// SQLWCHAR type as declared in include/sqltypes.h:467
type SQLWCHAR uint16

// SQLTCHAR type as declared in include/sqltypes.h:472
type SQLTCHAR byte
