name: Build
on: [push]
jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install unixodbc libraries
        run: sudo apt-get install -y libssl-dev unixodbc-dev unixodbc
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...        

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go test -v ./ ./internal/cache -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
